### ISSUE TITLE
Words Don't load from JSON

### ISSUE THREAD

**Issue by 8spw** [Jortsoft/Catch-Word-js#1]

**Comment by callmenikk** [comment]
ეს იმ შემთხვევაში თუ პირადაპირ index.html-ს ხსნი თორე Live-server-დან მუშაობს

**Comment by callmenikk** [comment]
აჰჰ უი არ წამიკითხავს Readme.md

**Comment by Jortsoft** [comment]
Are you sure my project run with live server? 😅

**Comment by 8spw** [comment]
I opened issue before reading documentation, my bad, I closed after that
